export class ActionTypes {
  public static readonly LOGIN_REDIRECT = 'LOGIN_REDIRECT'
  public static readonly CURRENT_ROUTE = 'CURRENT_ROUTE'
  public static readonly REGISTER = 'REGISTER'
  public static readonly LOGIN = 'LOGIN'
  public static readonly LOGOUT = 'LOGOUT'
  public static readonly GET_USER = 'GET_USER'
  public static readonly GET_AUTHOR = 'GET_AUTHOR'
  public static readonly UPLOAD_AVATAR = 'UPLOAD_AVATAR'
  public static readonly GET_RECIPE_LIST = 'GET_RECIPE_LIST'
  public static readonly CREATE_RECIPE = 'CREATE_RECIPE'
  public static readonly UPDATE_RECIPE = 'UPDATE_RECIPE'
  public static readonly DELETE_RECIPE = 'DELETE_RECIPE'
  public static readonly RESET_RECIPE = 'RESET_RECIPE'
  public static readonly PUBLISH_RECIPE = 'PUBLISH_RECIPE'
  public static readonly UNPUBLISH_RECIPE = 'UNPUBLISH_RECIPE'
  public static readonly UPLOAD_COVER = 'UPLOAD_COVER'
  public static readonly UPDATE_PREVIOUS = 'UPDATE_PREVIOUS'

  public static readonly GET_RECIPE = 'GET_RECIPE'
  public static readonly GET_USER_RECIPE_LIST = 'GET_USER_RECIPE_LIST'
  public static readonly OPEN_ALERT = 'OPEN_ALERT'
  public static readonly CLOSE_ALERT = 'CLOSE_ALERT'
  public static readonly OPEN_DIALOG = 'OPEN_DIALOG'
  public static readonly CLOSE_DIALOG = 'CLOSE_DIALOG'
  public static readonly DEREGISTER_USER = 'DEREGISTER_USER'
}
